var valNumber = 25;
var valString = "Hello World";
var valBoolean = false;
var valUndefined = undefined;
console.log("Number:", valNumber * 2);
console.log("String:", valString.toUpperCase());
console.log("Boolean:", valBoolean);
console.log("Undefined:", valUndefined);
var dynamicValue = "500";
var convertedToNumber = parseInt(dynamicValue);
console.log("Converted to Number:", convertedToNumber);
var floatString = "45.67";
var convertedToFloat = parseFloat(floatString);
console.log("Converted to Float:", convertedToFloat);
var numValuenew = 789;
var convertedToString = numValuenew.toString();
console.log("Converted to String:", convertedToString);
var unknownValue = "900";
var assertedNumber = unknownValue;
console.log("Asserted Number:", assertedNumber);
